/*
 * use serde::Deserialize;

 * macro_rules! number_schema {
    ($name:ident, $numtype:ty) => {
        ///Autogenerated static serializable type string
        #[derive(Debug)]
        pub struct $name<const MIN: $numtype, const MAX: $numtype>($numtype);
        impl<'de, const MIN: $numtype, const MAX: $numtype> Deserialize<'de> for $name<MIN, MAX> {
            fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
            where
                D: serde::Deserializer<'de>,
            {
                <$numtype>::deserialize(deserializer).map(|num| Self(num))
            }
        }
        impl<const MIN: $numtype, const MAX: $numtype> From<$name<MIN, MAX>> for $numtype {
            fn from(value: $name<MIN, MAX>) -> Self {
                value.0
            }
        }
    };
}
number_schema!(SchemaFloat, f64);
pub struct SchemaInteger<const MIN: i64, const MAX: i64>(i64);
impl<const MIN: i64, const MAX: i64> From<SchemaInteger<MIN, MAX>> for i64 {
    fn from(value: SchemaInteger<MIN, MAX>) -> Self {
        value.0
    }
}
impl<'de, const MIN: i64, const MAX: i64> Deserialize<'de> for SchemaInteger<MIN, MAX> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        i64::deserialize(deserializer).map(|num| Self(num))
    }
}*/
