use crate::schema::generable::Generable;
///Generated by Generable
pub trait CachedGenerable: Generable {
    ///Returns a static str of the schema that acts like a serde_json::Value
    fn get_schema() -> Box<serde_json::value::RawValue>;
}
